import type { Metadata } from 'next';
import { Providers } from '@/redux/provider';

import NavBar from './components/subcomponents/NavBar/NavBar';
import Footer from './components/subcomponents/Footer/Footer';
import { ChatBotProps } from './components/subcomponents/ChatBot/ChatBot';
import ChatBotButton from './components/subcomponents/ChatBotButton/ChatBotButton';

import './styles/globals.scss';

export const metadata: Metadata = {
	title: 'Chatbase | Custom ChatGPT for your data',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	const chatBotProps: ChatBotProps = {
		botName: 'Chatbase',
		iconUrl: '/chatbase.svg',
	};

	return (
		<html lang="en">
			<head>
				<link rel="icon" href="/favicon.ico" sizes="any" />
			</head>
			<body>
				<NavBar />
				<Providers>
					<main>{children}</main>
					<ChatBotButton chatBotProps={chatBotProps} />
				</Providers>
				<Footer />
			</body>
		</html>
	);
}
